### ISSUE TITLE
ARM wheels

### ISSUE THREAD

**Issue by timka** [timka/watchdogdev#4]
It would be valuable for the project to have pre-built ARM wheels.

Maybe [piwheels](http://piwheels.org) is a way to go.

**Comment by DoubleAJ** [comment]
It is. After you uploaded the source distribution, piwheels automatically built the arm wheels, and made them available for download on pip. Pretty cool stuff!
I tried to use the installed package and it works well. Here is the output of my installation:
```
pi@raspberrypi:~$ python3 -m pip install watchdogdev
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting watchdogdev
  Downloading https://www.piwheels.org/simple/watchdogdev/watchdogdev-1.0.0-cp37-cp37m-linux_armv6l.whl (23 kB)
Installing collected packages: watchdogdev
Successfully installed watchdogdev-1.0.0
```

Thank you @timka !

**Comment by timka** [comment]
Oh, wow! :) Impressive!
